### PR TITLE
Updated lib.io with some much needed information :)

### PR DESCRIPTION
**Pull request by poemdexter**

### CODE REVIEW

**Comment by krainboltgreene** [comment]
Haha,  but seriously...Hmm. Author + Contributor? I'm game. Checkout the git branch and look at the new syntax.

**Comment by poemdexter** [comment]
Why do you keep accepting my pull requests that are just comments?

**Comment by krainboltgreene** [comment]
Huh? This isn't a comment?

**Comment by poemdexter** [comment]
But I haven't really contributed anything of substance.  I can make 50 commits of empty directories and empty text files and you'd accept them just fine.  WHY ARE YOU TROLLING ME?!?!

**Comment by krainboltgreene** [comment]
Er, I'm confused. I'm not trolling you? I just don't mind small commits.

**Pull request closed without merging**
